### ISSUE TITLE
Add support for PHP 8.3 and WordPress 6.5.2

### ISSUE THREAD

**Issue by bobbingwide** [bobbingwide/cookie-category#3]
cookie-category was last updated a long time ago, when it was tested with PHP 7.1
Now we need to test with PHP 8.3.

See also https://github.com/bobbingwide/bobbingwide/issues/114

Note: I was considering dropping the domain cookie-cat.co.uk but decided to retain it... 
- it only costs £12 to renew for two years
- the work to test the support for PHP 8.3 is more important

**Comment by bobbingwide** [comment]
Messages when cookie-category was first activated in PHP 8.3 were

PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in C:\apache\htdocs\wordpress\wp-content\plugins\cookie-category\cookie-category.php on line 72 
and 8 other lines

Subsequently, the simplexml_load_file() was failing with a 404, which caused several more errors in the client.
The messages in the server were


```
30-Apr-2024 14:10:44 UTC] PHP Deprecated:  File C:\apache\htdocs\wordpress\wp-content\plugins\oik\includes\bw_posts.inc is deprecated since version 3.2.1! Use includes/bw_posts.php instead. Please use includes/bw_posts.php in C:\apache\htdocs\wordpress\wp-includes\functions.php on line 6078
[30-Apr-2024 14:10:51 UTC] PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in C:\apache\htdocs\wordpress\wp-content\plugins\cookie-category\feed\cookie-category-feed.php:313
Stack trace:
#0 C:\apache\htdocs\wordpress\wp-content\plugins\cookie-category\feed\cookie-category-feed.php(455): oik_cc_mapping_cookies()
#1 C:\apache\htdocs\wordpress\wp-content\plugins\cookie-category\cookie-category.php(265): oik_lazy_cc_mapping_feed()
#2 C:\apache\htdocs\wordpress\wp-includes\class-wp-hook.php(324): oik_cc_mapping_feed(false, 'cc_mapping')
#3 C:\apache\htdocs\wordpress\wp-includes\class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#4 C:\apache\htdocs\wordpress\wp-includes\plugin.php(517): WP_Hook->do_action(Array)
#5 C:\apache\htdocs\wordpress\wp-includes\functions.php(1632): do_action('do_feed_cc_mapp...', false, 'cc_mapping')
#6 C:\apache\htdocs\wordpress\wp-includes\template-loader.php(48): do_feed()
#7 C:\apache\htdocs\wordpress\wp-blog-header.php(19): require_once('C:\\apache\\htdoc...')
#8 C:\apache\htdocs\wordpress\index.php(17): require('C:\\apache\\htdoc...')
#9 {main}
  thrown in C:\apache\htdocs\wordpress\wp-content\plugins\cookie-category\feed\cookie-category-feed.php on line 313
```

**Comment by bobbingwide** [comment]
Delivered in v1.3.0
